name: Report a Bug
description: Report an issue with the Salesforce Code Analyzer Extension
title: "[BUG] <YOUR_TITLE_HERE>"
labels: []
body:
- type: textarea
  attributes:
    label: Bug Description
    description: Provide a clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List out the steps that you used to reproduce the bug behavior. Be as specific and clear as possible.
    placeholder: |
      1. I first do ...
      2. Then I do ...
      3. Lastly, I do ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: Provide a clear and concise description of what you expected to happen.
- type: input
  attributes:
    label: Operating System
    description: |
      What is your machine's operating system?
    placeholder: |
      Example: MacOS Sonoma 14.4.1
  validations:
    required: true
- type: input
  attributes:
    label: Visual Studio Code Version
    description: |
      What version do you find from clicking on "Code > About Visual Studio Code"?
    placeholder: |
      Example: Version: 1.89.1 (Universal)
  validations:
    required: true
- type: input
  attributes:
    label: Salesforce Code Analyzer Extension Version
    description: |
      What version do you find from clicking "Code > Settings > Extensions > 'Salesforce Code Analyzer'"?
    placeholder: |
      Example: v0.5.0
  validations:
    required: true
- type: input
  attributes:
    label: Salesforce CLI Version
    description: |
      What do you get from typing the command "sf --version" in the terminal?
    placeholder: |
      Example: @salesforce/cli/2.40.7 darwin-arm64 node-v20.12.2
  validations:
    required: true
- type: input
  attributes:
    label: Code Analyzer CLI Plugin (@salesforce/sfdx-scanner) Version
    description: |
      What do you get from typing the command "sf plugins" in the terminal?
    placeholder: |
      Example: @salesforce/sfdx-scanner 4.1.0 (latest-beta)
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context (Screenshots, Files, etc)
    description: Add any other context about the problem.
    placeholder: |
      Drag any files or screenshots you have here.
- type: textarea
  attributes:
    label: Workaround
    description: What ways have you found to sidestep the problem? If you haven't found a workaround, what have you tried so far?
- type: dropdown
  attributes:
    label: Urgency
    description: What is the severity of the problem?
    options:
    - Low
    - Moderate
    - High
    - Critical
    default: 0
  validations:
    required: true
