blank_issues_enabled: false
contact_links:
  - name: Report a Bug
    url: https://github.com/forcedotcom/code-analyzer/issues/new?template=2-vscode_extension_bug.yml
    about: Create an issue in our main repository.
  - name: Request a New Feature
    url: https://github.com/forcedotcom/code-analyzer/issues/new?template=5-feature_request.yml
    about: Request a feature in our main repository.
