/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public class MyClass1 {
    public static boolean someBooleanMethod() {
        return false;
    }

    public static boolean methodWithComment() { // Behold the glory of this comment. Gaze upon it.
        return true;
    }
}
