/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public class MyClass2 {

    public static boolean someBooleanMethod() {
        // some comment that includes public class MyClass2 {
        return false;
    }
    /* some other comment in a single line */
    public static boolean someOtherBooleanMethod() {
        /*
        some other comment that includes public class MyClass 2 {
        */
        return false;
    }

    public static boolean someOtherMethod() {
        public static String someString = 'this string has class MyClass2 { ';
        return true;
    }
}
