/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class MyClassA1 {
    public static boolean beep() {
        return true;
    }

    public static boolean boop() {
        return false;
    }

    public boolean instanceBoop() {
        return true;
    }
}