name: build-scanner-tarball
on:
  workflow_call:
    inputs:
      target-branch:
        description: "Which branch of the scanner should be built?"
        required: false
        type: string
        default: "dev-4"

jobs:
  build-tarball:
    runs-on: ubuntu-latest
    steps:
      # Install Node and Java.
      - name: 'Install Node LTS'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Always use Node LTS for building the tarball.
      - name: 'Install Java v11'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11' # Always use Java v11 for building the tarball.
      - name: 'Check out, build, pack'
        run: |
          # Check out the target branch.
          git clone -b ${{ inputs.target-branch }} https://github.com/forcedotcom/sfdx-scanner.git sfdx-scanner
          cd sfdx-scanner
          # Install and build dependencies.
          if [["${{ inputs.target-branch}}" == "dev-4"]]; then
            yarn
            yarn build
          else
            npm install
            npm run build
          fi
          # Create the tarball.
          npm pack
      # Upload the tarball as an artifact so it's usable elsewhere.
      - uses: actions/upload-artifact@v4
        with:
          name: scanner-tarball-${{ inputs.target-branch }}
          path: ./**/salesforce-*.tgz
