name: build-tarball
on:
  workflow_call:
    inputs:
      target-branch:
        description: "Which branch of code analyzer should be built?"
        required: false
        type: string
        default: "dev"

jobs:
  build-tarball:
    runs-on: ubuntu-latest
    steps:
      # Install Node and Java.
      - name: 'Install Node LTS'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Always use Node LTS for building the tarball.
      - name: 'Install Java v11'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11' # Always use Java v11 for building the tarball.
      - name: 'Install Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Minimum version required by code-analyzer.
      - name: 'Check out, build, pack'
        run: |
          # Check out the target branch.
          git clone -b ${{ inputs.target-branch }} https://github.com/forcedotcom/code-analyzer.git code-analyzer
          cd code-analyzer
          # Install and build dependencies.
          npm install
          npm run build
          # Create the tarball.
          npm pack
      # Upload the tarball as an artifact so it's usable elsewhere.
      - uses: actions/upload-artifact@v4
        with:
          name: tarball-${{ inputs.target-branch }}
          path: ./**/salesforce-*.tgz
