name: create-vsix-artifact
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the code'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.IDEE_GH_TOKEN }} # So we can access internal repo to pull shared ui components
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Node LTS should always be fine.
      - name: 'Install node dependencies'
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.IDEE_GH_TOKEN }}" > ~/.npmrc
          yarn install --frozen-lockfile
      - name: 'Create VSIX'
        run: npx vsce package
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: ./sfdx-code-analyzer-vscode-*.vsix
      - run: |
          find . -type f -name "*.vsix" -exec shasum -a 256 {} \; >> SHA256
          echo SHA INFO `cat SHA256`



