name: create-vsix-artifact
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
    steps:
      - name: 'Check out the code'
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Node LTS should always be fine.
      - name: 'Force fetch the private repo dependency'
        run: yarn add https://${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}@github.com/forcedotcom/salesforcedx-vscode-einstein-shared#semver:0.3.10 --no-save --no-lockfile
      - name: 'Install the rest of the node dependencies'
        run: yarn install
      - name: 'Create VSIX'
        run: npx vsce package
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: ./sfdx-code-analyzer-vscode-*.vsix
      - run: |
          find . -type f -name "*.vsix" -exec shasum -a 256 {} \; >> SHA256
          echo SHA INFO `cat SHA256`



