name: Publish v0.2.0 to OpenVSX marketplace
on:
  # Should only be possible to run this action manually.
  workflow_dispatch:

jobs:
  publish-openvsx:
    name: 'Publish to OpenVSX marketplace'
    # The `publish` environment is inherited from the org level, and means the job
    # can't proceed until someone with appropriate permissions approves it.
    environment: publish
    runs-on: ubuntu-latest
    env:
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
      GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
    steps:
      - name: Check out the release tag
        uses: actions/checkout@v3
        with:
          ref: 'v0.2.0'
          token: ${{ env.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: yarn install --frozen-lockfile
      - name: Download Extension from Release
        run: |
          mkdir ./extensions
          gh release download v0.2.0 -D ./extensions
      - name: Display downloaded VSIX
        run: ls -R ./extensions
      - name: Publish the VSIX
        run: find ./extensions -type f -name "*.vsix" -exec npx ovsx publish {} -p ${{ env.OVSX_PAT}} \;
      - run: echo "SUCCESSFULLY PUBLISHED"

