name: production-heartbeat
on:
  workflow_dispatch: # As per documentation, the colon is necessary even though no config is required.
  schedule:
    # Cron syntax is "minute[0-59] hour[0-23] date[1-31] month[1-12] day[0-6]". '*' is 'any value', and multiple values
    # can be specified with comma-separated lists. All times are UTC.
    # So this expression means "run at 45 minutes past 1, 5, and 9 AM/PM UTC". The hours were chosen so that
    # the jobs run only close to business hours of Central Time.
    # Days were chosen to run only from Monday through Friday.
    - cron: '45 13,17,21 * * 1,2,3,4,5'
jobs:
  production-heartbeat:
    strategy:
      # By default, if any job in a matrix fails, all other jobs are immediately cancelled. This makes the jobs run to completion instead.
      fail-fast: false
      matrix:
        os: [{vm: ubuntu-latest, exe: .sh}, {vm: windows-2019, exe: .cmd}]
        node: ['lts/*']
    runs-on: ${{ matrix.os.vm }}
    timeout-minutes: 60
    steps:
      # === Setup. We need to get the code, set up nodejs, and create the results directory. ===
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: mkdir smoke-test-results

      - name: Install VS Code
        run: |
          sudo apt update
          sudo apt install wget gpg -y
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
          sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
          sudo apt update
          sudo apt install code -y

      - name: Install Salesforce Code Analyzer Extension
        run: |
          code --install-extension salesforce.sfdx-code-analyzer-vscode

      - name: Verify Extension Installation
        run: |
          if code --list-extensions | grep -q 'salesforce.sfdx-code-analyzer-vscode'; then
            echo "Extension installed successfully"
          else
            echo "Extension installation failed" && exit 1
          fi
