name: run-tests
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-run:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out the code'
        uses: actions/checkout@v3
      - name: 'Set up NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Node LTS should always be fine.
      - name: 'Install node module dependencies'
        run: yarn install --frozen-lockfile
      # Install the CLI tool and SFCA, since there are integration tests
      # that depend on these things being present.
      - name: Install SF CLI
        run: npm install --global @salesforce/cli
      - name: Install Code Analyzer
        run: sfdx plugins:install @salesforce/sfdx-scanner
      # Run the tests. (Linux and non-Linux need slightly different commands.)
      - name: 'Run Tests (Linux)'
        run: xvfb-run -a yarn test
        if: runner.os == 'Linux'
      - name: 'Run Tests (non-Linux)'
        run: yarn test
        if: runner.os != 'Linux'
      # Lint, to make sure we're following best practices.
      - name: 'Lint'
        run: yarn lint
      # Upload the code coverage from the test as an artifact with
      # the name 'code-coverage-[whatever the OS is]'.
      - name: Upload coverage artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ runner.os }}
          path: ./coverage

