name: validate-pr
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  # We need to verify that the Pull Request's title matches the desired format.
  verify_pr_title:
    runs-on: ubuntu-latest
    name: Verify that PR title contains well-formed GUS work item tag.
    steps:
      # Private actions must check out repo first.
      - name: Checkout
        uses: actions/checkout@v3
      # TODO: Implement this action
      - name: Verify PR Title
        run: echo 'Nope not yet'
  # Separately, we also need to run our tests
  run_tests:
    name: 'Run unit tests'
    uses: ./.github/workflows/run-tests.yml
  # Additionally, build a VSIX that can be downloaded by the user if needed.
  create-vsix-artifact:
    name: 'Upload VSIX as artifact'
    uses: ./.github/workflows/create-vsix-artifact.yml
