name: validate-pr
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  # VALIDATE PR TITLE FORMAT
  verify_pr_title:
    runs-on: ubuntu-latest
    name: Verify that PR title contains well-formed GUS work item tag.
    steps:
      # Private actions must check out repo first.
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify PR Title
        uses: ./github-actions/verify-pr-title
        id: verify_pr_title
  # RUN TESTS
  # Step 1: Build the scanner tarball so it can be installed locally.
  build_scanner_tarball:
    name: 'Build scanner tarball'
    uses: ./.github/workflows/build-scanner-tarball.yml
    with:
      target-branch: 'dev'
  # Step 2: Actually run the tests.
  run_tests:
    name: 'Run unit tests'
    needs: build_scanner_tarball
    uses: ./.github/workflows/run-tests.yml
    with:
      # We want to validate the extension against whatever version of the scanner we
      # *plan* to publish, not what's *already* published.
      use-scanner-tarball: true
  # BUILD A VSIX ARTIFACT
  # Additionally, build a VSIX that can be downloaded by the user if needed.
  create-vsix-artifact:
    name: 'Upload VSIX as artifact'
    uses: ./.github/workflows/create-vsix-artifact.yml
